services:
  - type: web
    name: arf-vet-booking-management-system
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_SKIP_CREATE
        value: true
      - key: DB_SSL
        value: true
      - key: DB_SSL_REJECT_UNAUTHORIZED
        value: true
